### ISSUE TITLE
Chai's inventory sorter mistakenly combines various packages, leading to lost items.

### ISSUE THREAD

**Issue by Classy-Cube** [pajicadvance/affogato#1]
https://github.com/pajicadvance/affogato/assets/13388890/d489aa6c-961d-4dff-b9af-18bb4506f214

Affogato version 1.0.7 
Also, I just wanted to say thanks for all the effort you put into the modpack - I've been loving it.

**Comment by pajicadvance** [comment]
Yikes, that's a bad one... I'll bring it up to Chai, they can likely fix this with an update.

**Comment by pajicadvance** [comment]
This seems to also affect items which are made stackable by the modpack, such as potions and enchanted books. I've temporarily pulled back version 1.0.7 until this gets resolved.

**Comment by pajicadvance** [comment]
1.0.8 is now out, containing a fix for this, on top of other fixes. Thanks for taking your time to report all of these issues!
