### ISSUE TITLE
Disenchanting equipment into a book is still possible with insufficient levels.

### ISSUE THREAD

**Issue by Classy-Cube** [pajicadvance/affogato#2]
Is this on purpose to help players who can't meet the level requirements or just a bug? 

https://github.com/pajicadvance/affogato/assets/13388890/a869bc76-3c52-460c-a496-6884d9f24ff0

In the video, I had 11 levels to show that disenchanting removes them, but you can still do it with no levels at all.
Affogato version 1.0.7

**Comment by pajicadvance** [comment]
Seems like a conflict between Charm and Grind Enchantments, somehow Charm is still modifying the enchantment extraction rules even when that feature is disabled via the config. Thanks for the report, I'll look into it later today.
