### ISSUE TITLE
Storage labels lose their images after leaving and returning to the world.

### ISSUE THREAD

**Issue by Classy-Cube** [pajicadvance/affogato#3]
https://github.com/pajicadvance/affogato/assets/13388890/42b9195c-b65c-4c5e-a9d4-653f25cf2359

Even when I used Storage Labels alone on Minecraft 1.20.1, this issue happened four out of five times upon rejoining the world. The Storage label dev has given up on fixing this bug, despite several user complaints on his [Github](https://github.com/MehVahdJukaar/labels-multi/issues/33).

![image](https://github.com/pajicadvance/affogato/assets/13388890/b1f29fa4-b9e6-4fdc-b128-70f81d95297d)

**Comment by pajicadvance** [comment]
Can't really do anything about this one by myself, besides removing the mod for now - at this point, it's entirely possible that there's an underlying Fabric bug that's causing this and it's not Storage Label's fault.
