### ISSUE TITLE
The Collection enchantment doesn't automatically pick up drops from mined blocks.

### ISSUE THREAD

**Issue by Classy-Cube** [pajicadvance/affogato#4]
Seems like there's a mod conflict that's messing up the Collection enchantment from the Charm mod. I could use the enchant fine when I used Charm on its own. 

https://github.com/pajicadvance/affogato/assets/13388890/ef21d6a8-9ab6-4d5e-8602-300b348dc110

Affocato version 1.0.6

**Comment by pajicadvance** [comment]
That must be a recent breakage, since it was tested working on release 1.0.0 and a few versions afterwards. Will check it out.
