### ISSUE TITLE
The guidebook should mention the high cost of disenchanting equipment

### ISSUE THREAD

**Issue by Classy-Cube** [pajicadvance/affogato#5]
I found this issue that's not really a bug, but more about explaining the modpack's enchanting changes well. So, while playing the game, I got enough diamonds to make gear and then moved my enchantments, which only needed 16 levels for my armor. But then I realized they were breaking faster than expected, and I didn't have enough material to fix them all. So to conserve for the equipment I thought was most valuable, I thought I'd go with iron equipment again. 

When I tried moving the enchantments from my gear, the experience cost was insane. Just to transfer the enchantments from my armor, it was gonna be 58 levels. I accepted that I was hasty upgrading my equipment without considering how much it would cost to fix, and so I should face some consequences, but 58 levels. Honestly, I couldn't be bothered to grind just to get my enchanted iron armor back, so I took advantage of the [grindstone bug](https://github.com/pajicadvance/affogato/issues/2) before it got fixed. 

The way I see it, the guidebook's enchanting section should give players a heads up about having plenty of repair materials before enchanting gear, since the cost of removing enchantments is high, I assume to balance mob drops with enchantments. Oh, and you should definitely mention the buffs for gold tools. I mean, who would ever craft them without knowing? (+300% durability, +166.67% speed, and +150% sword attack speed)

**Comment by Classy-Cube** [comment]
Is it feasible to let the anvil move enchantments from one gear to another? I can't find any such mod so I'm guessing this isn't doable. 
<img src="https://github.com/pajicadvance/affogato/assets/13388890/fe5dfcfa-da0a-49e1-a34c-7df9fabd060f" width="300">

**Comment by pajicadvance** [comment]
Probably, but I really don't want to implement it that way.

The XP cost for disenchanting equipment is configurable in the Grind Enchantments mod config. I'm going to play around with the values to see how it affects the cost. Which enchantments did you have on your armor when it cost 58 levels to disenchant?

By the way, seeing that you have a lot of feedback, I also have a [Discord server](https://discord.gg/5RkzS66zWb) for the modpack, if you'd prefer a more live discussion.

**Comment by Classy-Cube** [comment]
> Which enchantments did you have on your armor when it cost 58 levels to disenchant?

To remove the enchants from my diamond armor:
Blast proc. 2 = 12 levels | Melee proc. 4 = 19 levels | Project proc. 4 = 15 levels | Aerial and Feather 2 = 12 levels
Totaling 58 levels

>I also have a Discord server for the modpack, if you'd prefer a more live discussion.

Thanks! ~~Speaking of which, your Discord link is expired on your modpack page :P~~ 
Never mind it must be some issue with the Opera browser or one of my extensions. I'll figure out how to fix that and connect later.

**Comment by Classy-Cube** [comment]
Wait did you fix your Discord link? Because now it works for my Opera browser, so it really was expired.

**Comment by pajicadvance** [comment]
Ah, I see, so it's not 58 levels outright, but rather a total for each piece of armor. In that case, the cost doesn't seem too far off from what I wanted, however it's probably worth looking into bumping it down a bit.

**Comment by pajicadvance** [comment]
> Wait did you fix your Discord link? Because now it works for my Opera browser, so it really was expired.

Yes, but it has been fixed for a while now, you probably tried it a while ago.

**Comment by pajicadvance** [comment]
Disenchanting costs have been addressed in version 1.0.10.
